version = 0.1
[default]
[default.global.parameters]
stack_name = "qs-aws-serverless"

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "qs-aws-serverless"
region = "ca-central-1"
image_repositories = []
