name: CI/CD On Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true
env:
  environment: dev
  TF_VERSION: 1.4.4
  TG_VERSION: 0.45.0
  TF_LOG: TRACE
  TG_CLIENT_SRC_PATH: client/terragrunt
  TG_WORKSPACE: sandbox
  

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:

  build-deploy-frontend:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN }}
          aws-region: ca-central-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Building front-end
        run: |
          cd client
          npm install
          npm run build
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.1
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Apply
        working-directory: ${{ env.TG_CLIENT_SRC_PATH }}/${{ env.TG_WORKSPACE }}
        env:
          app_version: ${{ github.event.number }}
          target_env: ${{ github.event.number }}
          s3_bucket: ${{ env.S3_BUCKET }}
          s3_bucket_assets: ${{ env.S3_BUCKET_ASSETS }}
          api_gateway_path_pattern: ${{ env.API_GATEWAY_PATH_PATTERN }}
          origin_id_assets: ${{ env.ORIGIN_ID_ASSETS }}
        run: terragrunt apply-all --terragrunt-non-interactive
